TARGET := 2ship2harkinian

SOURCE_FOLDERS := mm/src/overlays/gamestates mm/src/overlays/kaleido_scope mm/src/overlays/actors \
	mm/src/overlays/effects mm/src/overlays/fbdemos

ZAPD_INCLUDES := ZAPDTR/ZAPD ZAPDTR/lib/libgfxd

ZAPD_SOURCES := ZAPDTR/ZAPD ZAPDTR/ZAPD/ZRoom ZAPDTR/ZAPD/ZRoom/Commands ZAPDTR/ZAPD/yaz0 ZAPDTR/ZAPD/OtherStructs \
	ZAPDTR/ZAPD/Utils

LUS_INCLUDES := libultraship/include libultraship/src libultraship/src/utils/binarytools libultraship/src/resource/type \
	libultraship/src/resource libultraship/src/window libultraship/src/window/gui libultraship/src/audio libultraship/src/graphic \
	libultraship/src libultraship/imgui libultraship/imgui/backends libultraship/src/public/bridge

LUS_SOURCES := libultraship/src libultraship/src/audio libultraship/src/config libultraship/src/graphic/Fast3D/debug \
	libultraship/src/debug libultraship/src/menu libultraship/src/utils libultraship/src/utils/binarytools \
	libultraship/src/resource libultraship/src/resource/type libultraship/src/resource/factory \
	libultraship/src/window libultraship/src/window/gui libultraship/src/config libultraship/src/public \
	libultraship/src/public/libultra libultraship/src/public/bridge libultraship/src/graphic/Fast3D \
	libultraship/src/log libultraship/imgui libultraship/src/controller/controldevice libultraship/src/window/gui/resource \
	libultraship/src/controller/controldevice/controller libultraship/src/controller/controldevice/controller/mapping \
	libultraship/src/controller/controldevice/controller/mapping/sdl libultraship/src/controller/controldevice/controller/mapping/factories \
	libultraship/src/controller/controldevice/controller/mapping/keyboard libultraship/src/controller/controldevice/controller/mapping/mouse \
	libultraship/src/controller/deviceindex libultraship/src/controller/controldeck libultraship/src/resource/archive

SOURCES	:= $(foreach dir,$(SOURCE_FOLDERS), $(wildcard $(dir)/*)) $(LUS_SOURCES) $(ZAPD_SOURCES) \
	mm/src/audio mm/src/audio/lib mm/src/code mm/2s2h mm/2s2h/BenGui mm/2s2h/Enhancements \
	mm/2s2h/Enhancements/FrameInterpolation mm/2s2h/Enhancements/Cheats mm/2s2h/Enhancements/Camera \
	mm/2s2h/Enhancements/Cutscenes mm/2s2h/Enhancements/Cutscenes/StoryCutscenes mm/2s2h/Enhancements/Cycle \
	mm/2s2h/Enhancements/Cutscenes/MiscInteractions mm/2s2h/Enhancements/Dialogue mm/2s2h/Enhancements/Equipment \
	mm/2s2h/Enhancements/DifficultyOptions mm/2s2h/Enhancements/Fixes mm/2s2h/Enhancements/GfxPatcher \
	mm/2s2h/Enhancements/Graphics mm/2s2h/Enhancements/Masks mm/2s2h/Enhancements/Minigames mm/src/buffers \
	mm/2s2h/Enhancements/Modes mm/2s2h/Enhancements/Player mm/2s2h/Enhancements/Restorations mm/2s2h/resource/type \
	mm/2s2h/Enhancements/Saving mm/2s2h/Enhancements/Songs mm/2s2h/Enhancements/Trackers mm/src/boot \
	mm/2s2h/DeveloperTools mm/2s2h/GameInteractor mm/2s2h/NameTag mm/2s2h/SaveManager mm/src/boot/O2 \
	mm/2s2h/NameTag mm/2s2h/SaveManager/Migrations mm/2s2h/resource/importer mm/2s2h/resource/type/scenecommand \
	mm/2s2h/resource/importer/scenecommand vita
	
INCLUDES := $(LUS_INCLUDES) $(ZAPD_INCLUDES) \
	mm/include/PR mm/include  mm/assets mm/src  spdlog/include mm/2s2h mm vita 

LIBS = -lstorm -lgfxd -lbzip2 -lzip -lzstd -lz -llzma -lssl -lcrypto -lstdc++ -lpng -Wl,--whole-archive -lpthread -Wl,--no-whole-archive \
	-ltinyxml2 -lSDL2 -lvitaGL -lvitashark -lSceShaccCgExt -ltaihen_stub -lmathneon -lSceAudioIn_stub -lSceIme_stub \
	-lSceKernelDmacMgr_stub -lSceGxm_stub -lSceDisplay_stub -lSceTouch_stub -lSceHid_stub -lSceCtrl_stub -lSceNet_stub \
	-lSceNetCtl_stub -lSceCommonDialog_stub -lSceAudio_stub -lSceSysmodule_stub -lSceMotion_stub -lSceAppUtil_stub \
	-lSceAppMgr_stub -lSceShaccCg_stub -lScePower_stub

FINAL_SOURCES := f

CFILES   := $(foreach dir,$(SOURCES), $(wildcard $(dir)/*.c))
CPPFILES   := $(foreach dir,$(SOURCES), $(wildcard $(dir)/*.cpp))
OBJS     := $(CFILES:.c=.o) $(CPPFILES:.cpp=.o) \
	libultraship/imgui/backends/imgui_impl_opengl3.o \
	libultraship/imgui/backends/imgui_impl_sdl2.o
	
OBJS_PREPARE := $(CFILES:.c=.ok) $(CPPFILES:.cpp=.ok) \
	libultraship/imgui/backends/imgui_impl_opengl3.ok \
	libultraship/imgui/backends/imgui_impl_sdl2.ok
	
OBJS_CLEAN := $(CFILES:.c=.oc) $(CPPFILES:.cpp=.oc) \
	libultraship/imgui/backends/imgui_impl_opengl3.oc \
	libultraship/imgui/backends/imgui_impl_sdl2.oc
	
FINAL_OBJS := $(foreach dir,$(FINAL_SOURCES), $(wildcard $(dir)/*.o))

CVAR_PREFIX_RANDOMIZER_ENHANCEMENT := gRandoEnhancements
CVAR_PREFIX_RANDOMIZER_SETTING := gRandoSettings
CVAR_PREFIX_COSMETIC := gCosmetics
CVAR_PREFIX_AUDIO := gAudioEditor
CVAR_PREFIX_CHEAT := gCheats
CVAR_PREFIX_ENHANCEMENT := gEnhancements
CVAR_PREFIX_SETTING := gSettings
CVAR_PREFIX_WINDOW := gOpenWindows
CVAR_PREFIX_TRACKER := gTrackers
CVAR_PREFIX_DEVELOPER_TOOLS := gDeveloperTools
CVAR_PREFIX_GENERAL := gGeneral
CVAR_PREFIX_REMOTE := gRemote

GFX_UCODE := F3DEX_GBI_2

PREFIX  = arm-vita-eabi
CC      = $(PREFIX)-gcc
CXX      = $(PREFIX)-g++
CFLAGS  = -fno-lto -g -Wl,-q -O3 -ffast-math $(foreach dir,$(INCLUDES),-I$(dir)) \
		-Wno-narrowing -DIMGUI_IMPL_OPENGL_ES2 -DSPDLOG_ACTIVE_LEVEL=0 \
		-I$(VITASDK)/$(PREFIX)/include/SDL2 -DENABLE_OPENGL -D$(GFX_UCODE) \
		-DCVAR_PREFIX_RANDOMIZER_ENHANCEMENT=\"$(CVAR_PREFIX_RANDOMIZER_ENHANCEMENT)\" \
		-DCVAR_PREFIX_RANDOMIZER_SETTING=\"$(CVAR_PREFIX_RANDOMIZER_SETTING)\" \
		-DCVAR_PREFIX_COSMETIC=\"$(CVAR_PREFIX_COSMETIC)\" \
		-DCVAR_PREFIX_AUDIO=\"$(CVAR_PREFIX_AUDIO)\" \
		-DCVAR_PREFIX_CHEAT=\"$(CVAR_PREFIX_CHEAT)\" \
		-DCVAR_PREFIX_ENHANCEMENT=\"$(CVAR_PREFIX_ENHANCEMENT)\" \
		-DCVAR_PREFIX_SETTING=\"$(CVAR_PREFIX_SETTING)\" \
		-DCVAR_PREFIX_WINDOW=\"$(CVAR_PREFIX_WINDOW)\" \
		-DCVAR_PREFIX_TRACKER=\"$(CVAR_PREFIX_TRACKER)\" \
		-DCVAR_PREFIX_DEVELOPER_TOOLS=\"$(CVAR_PREFIX_DEVELOPER_TOOLS)\" \
		-DCVAR_PREFIX_GENERAL=\"$(CVAR_PREFIX_GENERAL)\" \
		-DCVAR_PREFIX_REMOTE=\"$(CVAR_PREFIX_REMOTE)\" \
		-DCVAR_VSYNC_ENABLED=\"gVsyncEnabled\" \
		-DCVAR_Z_FIGHTING_MODE=\"gZFightingMode\" \
		-DCVAR_NEW_FILE_DROPPED=\"gNewFileDropped\" \
		-DCVAR_DROPPED_FILE=\"gDroppedFile\" \
		-DCVAR_INTERNAL_RESOLUTION=\"gInternalResolution\" \
		-DCVAR_MSAA_VALUE=\"gMSAAValue\" \
		-DCVAR_SDL_WINDOWED_FULLSCREEN=\"gSdlWindowedFullscreen\" \
		-DCVAR_TEXTURE_FILTER=\"gTextureFilter\" \
		-DCVAR_IMGUI_CONTROLLER_NAV=\"gControlNav\" \
		-DCVAR_CONSOLE_WINDOW_OPEN=\"gConsoleEnabled\" \
		-DCVAR_CONTROLLER_CONFIGURATION_WINDOW_OPEN=\"gControllerConfigurationEnabled\" \
		-DCVAR_CONTROLLER_DISCONNECTED_WINDOW_OPEN=\"gControllerDisconnectedWindowEnabled\" \
		-DCVAR_CONTROLLER_REORDERING_WINDOW_OPEN=\"gControllerReorderingWindowEnabled\" \
		-DCVAR_GFX_DEBUGGER_WINDOW_OPEN=\"gGfxDebuggerEnabled\" \
		-DCVAR_STATS_WINDOW_OPEN=\"gStatsEnabled\" \
		-DCVAR_ENABLE_MULTI_VIEWPORTS=\"gEnableMultiViewports\" \
		-DCVAR_LOW_RES_MODE=\"gLowResMode\" \
		-DCVAR_SIMULATED_INPUT_LAG=\"gSimulatedInputLag\" \
		-DCVAR_GAME_OVERLAY_FONT=\"gOverlayFont\" \
		-DCVAR_MENU_BAR_OPEN=\"gOpenMenuBar\" \
		-DCVAR_PREFIX_CONTROLLERS=\"gControllers\" \
		-DCVAR_PREFIX_ADVANCED_RESOLUTION=\"gAdvancedResolution\"

CXXFLAGS  = $(CFLAGS) -fexceptions -std=gnu++20 -fpermissive
ASFLAGS = $(CFLAGS)

all: $(TARGET).velf

prepare: f $(OBJS_PREPARE)

f:
	mkdir f

%.ok:
	$(eval gen_num=$(shell echo $$(($(gen_num)+1))))
	@cp $(@:k=) f/$(gen_num).o

%.oc:
	@rm -rf $(@:c=)

%.velf: %.elf
	cp $< $<.unstripped.elf
	$(PREFIX)-strip -g $<
	vita-elf-create $< $@
	vita-make-fself -c -s $@ eboot.bin

$(TARGET).elf: $(FINAL_OBJS)
	$(CXX) $(CXXFLAGS) $^ $(LIBS) -o $@

objects: $(OBJS)

clean: $(OBJS_CLEAN)
	@rm -rf $(TARGET).velf $(TARGET).elf $(FINAL_OBJS)
